import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next one App",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <h1 className="text-green-500">Users Layout</h1>
      <p className="text-green-500">
        This is the layout for the users section.
      </p>
      {children}
    </div>
  );
}
